go_import_path: github.com/jetstack/navigator

jobs:
  include:
    - stage: test
      dist: trusty
      language: go
      go: 1.8
      env:
      - KUBERNETES_VERSION=v1.7.0
      script:
      - set -e
      # Install nsenter
      - docker build -t ubuntu-nsenter ./hack/ubuntu-nsenter
      - docker run -v /usr/local/bin:/hostbin ubuntu-nsenter cp /nsenter /hostbin/nsenter
      - make BUILD_TAG=latest e2e-test

    - stage: test
      dist: trusty
      language: go
      go: 1.8
      script:
      - make verify

    - stage: build
      dist: trusty
      services:
      - docker
      language: go
      go: 1.8
      script:
      - make go_build docker_build
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
          mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json;
          make docker_push IMAGE_TAGS="${TRAVIS_COMMIT} latest";
        fi
