# Default values for navigator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jetstackexperimental/navigator
  tag: latest
  pullPolicy: IfNotPresent
resources: {}
