apiVersion: navigator.jetstack.io/v1alpha1
kind: CassandraCluster
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name"  . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  cqlPort: {{ .Values.cqlPort }}
  sysctls:
  - vm.max_map_count=0
  nodePools:
  - name: ringnodes
    replicas: {{ .Values.replicaCount }}
    persistence:
      size: {{ .Values.persistence.size }}
      storageClass: {{ .Values.persistence.storageClass }}
  image:
    repository: {{ .Values.image.repository | quote }}
    tag: {{ .Values.image.tag | quote }}
    pullPolicy: {{ .Values.image.pullPolicy | quote }}
  pilotImage:
    repository: {{ .Values.pilotImage.repository | quote }}
    tag: {{ .Values.pilotImage.tag | quote }}
    pullPolicy: {{ .Values.pilotImage.pullPolicy | quote }}
